#! /bin/sh

while [ 1 ];do
    # store the total and free memory in two variables
    read t <<< `grep -E 'MemTotal' /proc/meminfo |awk '{print $2}'`
    read f <<< `grep -E 'MemAvailable' /proc/meminfo |awk '{print $2}'`
    # then, calcultate the percentage of memory used
    
    used=$(($t -$f))
    bc=$((100*$used/$t))
    echo "R$bc"
    sleep 4
done
